### PR TITLE
React-virtualized for rendering tables

### PR DESCRIPTION
**Pull request by anuveyatsu**
Implemented `react-virtualized` library for rendering tables (instead of handsontables).

- setup `index.jsx` and fixed tests for it
- a new component `ReactVirtualized.jsx` + tests + snapshot for it

### CODE REVIEW

**Review by zelima — COMMENTED** [review]
I see we do not use `HandsOnTable` components at all, we don't even have tests for it any more. So should not we remove dependency from package.json and  `/components/dataPackageView/HandsOnTable.jsx` file itself ?

**Comment by zelima** [comment]
Also we are missing up to date `bundle.js`

**Comment by anuveyatsu** [comment]
@zelima we're replacing `handsontable` with `react-virtualized` now. But we have tests for it, see [here](https://github.com/frictionlessdata/dpr-js/blob/gh-pages/tests/components/dataPackageView/handsontable.test.jsx).
There are some disadvantages of `react-virtualized`, e.g. column size cannot be adjustable as in `handsontable`, so we need to agree that it's OK.. and also I think we need to have an option to switch between libraries in the future.

**Comment by zelima** [comment]
@anuveyatsu OK, got you. Let's add bundle and we are ready to go

**Pull request merged**
